In [6]:
import numpy as np

In [11]:
"""
The target is to maximize the accuracy of the cnn-mnist model:
    We start by having a few decisions related to the model. 
    x1 = 32 or 64 (or 128) filters in each CNN layer
    x2 = 50 or 100 neurons in first dense layer
    x3 = 1 or 2 CNN layers
    x4 = he_uniform or random_normal
    x5 = no dropout, (0.1 dropout,) 0.2 dropout
    x6 = learning rate 0.005, (0.01) or 0.05 
    x7 = kernel size cnn 2, 3
    We will use a genetic algorithm to find the best combinations of these hyperparameters. 
    The fitness-function is based on model accuracy on test-dataset. 
"""
num_weights = 7

# solutions per populations and number of mating parents
sol_per_pop = 8
num_parents_mating = 4

In [12]:
# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#Creating the initial population.
new_population = np.random.randint(low=0, high=2, size=pop_size)
print(new_population)

[[0 1 0 1 0 1 0]
 [1 1 1 0 1 0 1]
 [1 0 0 0 1 1 0]
 [1 0 1 1 1 1 0]
 [0 0 0 1 0 0 1]
 [0 0 0 0 0 0 1]
 [1 1 1 1 0 1 0]
 [0 1 0 0 1 1 0]]
